import 'package:ecommerce/data/models/address_model.dart';
import 'package:ecommerce/data/models/product_model.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('ProductModel.fromJson', () {
    test('reads the snake_case columns returned by Supabase', () {
      final p = ProductModel.fromJson({
        'id': 7,
        'name': 'iPhone 15',
        'category_name': 'Smartphones',
        'price': 999,
        'old_price': 1099.5,
        'rating': 4,
        'review_count': 12,
        'description': 'desc',
        'images': ['a.png', 'b.png'],
        'is_flash_deal': true,
      });

      expect(p.id, '7');
      expect(p.category, 'Smartphones');
      expect(p.price, 999.0);
      expect(p.oldPrice, 1099.5);
      expect(p.rating, 4.0);
      expect(p.reviewCount, 12);
      expect(p.images, ['a.png', 'b.png']);
      expect(p.isFlashDeal, isTrue);
    });

    test('also accepts camelCase keys', () {
      final p = ProductModel.fromJson({
        'id': 'x',
        'name': 'n',
        'category': 'Audio',
        'price': 1.5,
        'oldPrice': 2,
        'reviewCount': 3,
        'isFlashDeal': false,
      });

      expect(p.category, 'Audio');
      expect(p.oldPrice, 2.0);
      expect(p.reviewCount, 3);
    });

    test('falls back to safe defaults when columns are null', () {
      final p = ProductModel.fromJson({'id': null});

      expect(p.id, '');
      expect(p.name, '');
      expect(p.price, 0);
      expect(p.oldPrice, isNull);
      expect(p.images, isEmpty);
      expect(p.isFlashDeal, isFalse);
    });

    test('toJson round-trips through fromJson', () {
      final original = ProductModel.fromJson({
        'id': '1',
        'name': 'MacBook',
        'category': 'Laptop',
        'price': 1299,
        'oldPrice': 1399,
        'rating': 4.9,
        'reviewCount': 5,
        'description': 'd',
        'images': ['m.png'],
        'isFlashDeal': true,
      });
      final copy = ProductModel.fromJson(original.toJson());

      expect(copy.toJson(), original.toJson());
    });
  });

  group('AddressModel', () {
    final json = {
      'id': 3,
      'user_id': 'u1',
      'full_name': 'Omar',
      'phone_number': '059',
      'street_address': 'Main',
      'city': 'Gaza',
      'postal_code': '00970',
      'country': 'Palestine',
      'is_default': true,
    };

    test('fromJson maps every column', () {
      final a = AddressModel.fromJson(json);

      expect(a.id, '3');
      expect(a.userId, 'u1');
      expect(a.fullName, 'Omar');
      expect(a.isDefault, isTrue);
    });

    test('is_default defaults to false when missing', () {
      final a = AddressModel.fromJson({...json}..remove('is_default'));

      expect(a.isDefault, isFalse);
    });

    test('toJson never sends the id (it is generated by the database)', () {
      final out = AddressModel.fromJson(json).toJson();

      expect(out.containsKey('id'), isFalse);
      expect(out['user_id'], 'u1');
      expect(out['is_default'], isTrue);
    });
  });
}
